### ISSUE TITLE
Currently, julia setup is broken for coc unless the LanguageServer is pulled from master

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-julia#177]
I'm reporting just to inform that a install of coc-julia currently just leads to server restarts due to https://github.com/julia-vscode/LanguageServer.jl/issues/836. The current fix is to pick the LanguageServer from master as commented at https://github.com/julia-vscode/LanguageServer.jl/issues/836#issuecomment-835890329.

Given the issue is known, coc-julia could try to avoid it automatically.

**Comment by fannheyward** [comment]
@oblitum can you reproduce this with v0.8.1? I can setup Julia.LS with Julia 1.6.1 and coc-julia.

**Comment by oblitum** [comment]
Thanks, now everything is working smoothly.

**Comment by fannheyward** [comment]
The `cef0bd38d71220cc25eda32b2d8febc324b05834` commit was came from https://github.com/fannheyward/coc-julia/pull/153/files#diff-1c887c4b81b9e61442fffb274a9ad352dcbfbc6dd8cae2b62a882f0ae7b19956L48-L54, @wangl-cc do you know what's the commit from?

**Comment by wangl-cc** [comment]
This commit was came from an update by `julia` package manager. I have no idea why it didn't exist in `LanguageServer.jl` commit history. Maybe its commit history has been rewritten.

**Comment by wangl-cc** [comment]
I found that `julia` use tree hash instead of commit hash to identify the version of a repository.  The `cef0bd38d71220cc25eda32b2d8febc324b05834` is tree hash of commit [`c2162bfcabacf230767b4ef0170538ed060b3eaa`](https://github.com/julia-vscode/LanguageServer.jl/commit/c2162bfcabacf230767b4ef0170538ed060b3eaa). @fannheyward @pfitzseb
